apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-13T15:08:44Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "8908"
  uid: 73ab2e65-abad-4407-9fac-610e9896abee
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.98.254.138
  clusterIPs:
  - 10.98.254.138
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31331
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
